name: $(Year:yy)$(DayOfYear).$(Rev:r)
trigger: [release/v1]
pr: { branches: { include: [release/v1] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { vmImage: windows-latest }

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: pipelines/build/nuget-package.job.yaml@templates
        parameters:
          releaseBranchName: release/v1

  - stage: Release
    displayName: Release
    jobs: [ { template: pipelines/release/internal-nuget-package.job.yaml@templates } ]
    condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
